# Generated by Django 4.2.8 on 2025-12-01 07:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the automation', max_length=255)),
                ('campaign_name', models.CharField(blank=True, help_text='Campaign name', max_length=255)),
                ('automation_type', models.CharField(choices=[('birthday', 'Birthday Messages'), ('festival', 'Festival Greetings'), ('reminder', 'Payment Reminders'), ('followup', 'Follow-up Messages'), ('custom', 'Custom Campaign')], max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('draft', 'Draft')], default='draft', max_length=10)),
                ('schedule_type', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('specific_date', 'Specific Date'), ('on_event', 'On Event')], max_length=20)),
                ('cron_expression', models.CharField(blank=True, max_length=100, null=True)),
                ('specific_time', models.TimeField(blank=True, null=True)),
                ('specific_date', models.DateField(blank=True, null=True)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('message_template', models.TextField(help_text='Message template with variables like {{name}}')),
                ('target_contacts', models.JSONField(default=list, help_text='List of specific contact IDs to target')),
                ('target_groups', models.JSONField(default=list, help_text='List of group names to target')),
                ('send_to_all', models.BooleanField(default=False, help_text='Send to all contacts')),
                ('cta_buttons', models.JSONField(default=list, help_text='List of CTA buttons (max 3)')),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
                ('next_run', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Automation',
                'verbose_name_plural': 'Automations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AutomationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('partial', 'Partial Success')], max_length=20)),
                ('messages_sent', models.PositiveIntegerField(default=0)),
                ('total_contacts', models.PositiveIntegerField(default=0)),
                ('error_log', models.TextField(blank=True, null=True)),
                ('automation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='automations.automation')),
            ],
            options={
                'verbose_name': 'Automation Log',
                'verbose_name_plural': 'Automation Logs',
                'ordering': ['-run_time'],
            },
        ),
    ]
