# Generated by Django 4.2.8 on 2025-12-01 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automation',
            name='user',
        ),
    ]
