# Generated by Django 4.2.8 on 2025-12-01 08:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=128, null=True)),
                ('waba_id', models.CharField(max_length=64)),
                ('phone_number_id', models.CharField(max_length=64, unique=True)),
                ('display_phone_number', models.CharField(blank=True, max_length=32, null=True)),
                ('access_token', models.TextField()),
                ('auto_switch_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'business_numbers',
            },
        ),
        migrations.CreateModel(
            name='VirtualNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waba_id', models.CharField(max_length=64)),
                ('phone_number_id', models.CharField(max_length=64, unique=True)),
                ('access_token', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20)),
                ('quality_rating', models.CharField(choices=[('unknown', 'Unknown'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='unknown', max_length=20)),
                ('is_primary', models.BooleanField(default=False)),
                ('message_count_24h', models.IntegerField(default=0)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business_number', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_numbers', to='virtualnumbers.businessnumber')),
            ],
            options={
                'db_table': 'virtual_numbers',
                'indexes': [models.Index(fields=['is_primary'], name='virtual_num_is_prim_ced37e_idx')],
            },
        ),
    ]
