# Generated by Django 4.2.8 on 2025-12-01 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtualnumbers_unique', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='virtualnumber',
            name='business_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='virtual_numbers', to='virtualnumbers_unique.businessnumber'),
        ),
    ]
